### ISSUE TITLE
Problems when using max-width for container element

### ISSUE THREAD

**Issue by jjroelofs** [Schepp/box-sizing-polyfill#13]
I'm trying to use box-sizing-polyfill in a fluid grid. The code looks somewhat like this:

&lt;style&gt;
.region {
width:100%;
max-width:978px;
}

.block {
float:left;
}

.grid-1-3 {
width: 33.32%;
}
&lt;/style&gt;

&lt;div class=&quot;region&quot;&gt;
  &lt;div class=&quot;block grid-1-3&quot;&gt;&lt;/div&gt;
  &lt;div class=&quot;block grid-1-3&quot;&gt;&lt;/div&gt;
  &lt;div class=&quot;block grid-1-3&quot;&gt;&lt;/div&gt;
&lt;/div&gt;

When boxsizing.htc runs, suddenly the width of a block isn't 1/3 of 978px but 1/3 of 100%. So on a 1920x1080 monitor the block is ~640px wide instead of the 326 that it should be (=1/3 of 978).

**Comment by RonnieSan** [comment]
I get the same issue.  Max-width attribute it is ignored.

**Comment by Schepp** [comment]
Check out the new version I committed today. Does that work as expected?

**Comment by RonnieSan** [comment]
Works beautifully!  Thanks so much!  You just made my life 100x easier.

**Comment by Schepp** [comment]
Good :)
