### ISSUE TITLE
Fails in conjunction with focus/blur Javascript.

### ISSUE THREAD

**Issue by lewishowles** [Schepp/box-sizing-polyfill#24]
Been trying to debug why this fails horrendously on a website I'm building and come up with the following:

The case I've applied it to is a form, the inputs of which are wrapped in LIs (in an OL, of course), and I'm able to add certain classes such as 'share' to put two inputs on one line responsively. Great.

Our form inputs have border-color and box-shadow changes on hover and focus, giving the user some feedback, and when applying those styles to elements in IE7 with border-box and this polyfill, the widths of the items seem to be recalculated and they're shrunk every time you hover or focus - making the whole thing unusable.

Are there any suggestions? If not I'd have to go through all of my CSS and say 'don't do this for IE7, don't do that for IE7, don't use the placeholder plugin for IE7 (that also triggers this resize on focus)' etc.

EDIT: I'll see if I can get a test page up and running for it after work. Spent so long adding and removing things I need to get it back to the bare code.

**Comment by lewishowles** [comment]
Got a test page as stripped down as I can. It's something to do with any Javascript that modifies any property of the inputs on hover or focus - which because of the way our forms work means we can't use the polyfill for forms in IE7 (which is really all we use it for at the moment!)

The page below contains one input with some of our default styling (to give it padding that would normally exceed 100% but removed all classes etc), and a very small portion of the javascript that adds a 'blurred' class to the input when it's blurred (so that HTML5 invalid CSS doesn't activate on page load).

http://www.lewishowles.co.uk/demos/boxsizing.html

For some reason it's still making the input larger than the page - which is odd. But as you can see in IE7 each time you blur the input it shrinks it slightly. On some sites it's doing this on hover too and I can't work out what's causing that but I imagine it's related.

This also happens when using Mathias Bynens' placeholder plugin that changes the value of the input so it seems to trigger when any property of the input is changed (even classes and value).

**Comment by claicham** [comment]
I can't see your demo page and I'm not 100% sure if we have the exact same issue, but I had a case of shrinking form elements in IE7 when using this polyfill along with the jquery placeholder plugin. Once the placeholder plugin is removed, the polyfill works brilliantly.

Still looking for a resolution to my placeholders in IE7, but at least box sizing is now sorted!

Update: placeholder-augment working fine alongside the box-sizing polyfill - https://github.com/jethrolarson/placeholder-augment
