### ISSUE TITLE
Doesn't get applied in IE9 running in IE7 mode. 

### ISSUE THREAD

**Issue by olemarius** [Schepp/box-sizing-polyfill#5]
When I run IE9 in IE7 mode, the box-model doesn't work and the layout breaks.

**Comment by Schepp** [comment]
If you run in a real IE7 it will work. IE9 in IE7 != IE7 :)
Since many people were testing that "wrong" way, we've updated the polyfill to also work with IE9 in IE7 mode. So just redownload it.

**Comment by olemarius** [comment]
Hehe, yea that's what I figured, but it's awesome that you added it so people can be sure that it will work in IE7. I didn't really feel like installing another VM just for IE7, already got IE6 and IE8 ;P Thanks a lot, keep up the great work! :)
